import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {

    const val gradle_plugin : String = "com.android.tools.build:gradle:_"

    const val activity_compose: String = "androidx.activity:activity-compose:_"

    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    const val ui: String = "androidx.compose.ui:ui:_"

    const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    const val core_ktx: String = "androidx.core:core-ktx:_"

    const val hilt_navigation_compose: String = "androidx.hilt:hilt-navigation-compose:_"

    const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val mavericks: String = "com.airbnb.android:mavericks:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val play_services_auth: String = "com.google.android.gms:play-services-auth:_"

    const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    const val hilt_android: String = "com.google.dagger:hilt-android:_"

    const val hilt_android_gradle_plugin: String =
            "com.google.dagger:hilt-android-gradle-plugin:_"

    const val hilt_compiler: String = "com.google.dagger:hilt-compiler:_"

    const val firebase_auth_ktx: String = "com.google.firebase:firebase-auth-ktx"

    const val firebase_bom: String = "com.google.firebase:firebase-bom:_"

    const val firebase_firestore_ktx: String = "com.google.firebase:firebase-firestore-ktx"

    const val firebase_storage: String = "com.google.firebase:firebase-storage"

    const val firebase_storage_ktx: String = "com.google.firebase:firebase-storage-ktx"

    const val google_services: String = "com.google.gms:google-services:_"

    const val timber: String = "com.jakewharton.timber:timber:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val android_junit5: String = "de.mannodermaus.gradle.plugins:android-junit5:_"

    const val android_test_core: String = "de.mannodermaus.junit5:android-test-core:_"

    const val android_test_runner: String = "de.mannodermaus.junit5:android-test-runner:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val mockk_agent_jvm: String = "io.mockk:mockk-agent-jvm:_"

    const val junit_junit: String = "junit:junit:_"

    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    const val kotlinx_coroutines_play_services: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:_"

    const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"
}
