name : Android build

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop , master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run Test
        run: ./gradlew test --warning-mode=all --stacktrace

      - name: Build Project
        run : ./gradlew build --stacktrace

      - name: Notify on telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The workflow <b>${{ github.workflow }}</b> triggered by ${{ github.event_name }} on ${{ github.ref }} is ${{ job.status }}