name : Android build

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop , master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: 'adopt'

      - name: Run Test
        run: ./gradlew test --stacktrace

      - name: Build Project
        run : ./gradlew build --stacktrace